// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.resolve(__dirname, '.env') });
import { defineConfig } from "prisma/config";

function decodePrismaPostgresUrl(connectionString?: string) {
  if (!connectionString?.startsWith('prisma+postgres://')) {
    return connectionString;
  }

  try {
    const url = new URL(connectionString);
    const apiKey = url.searchParams.get('api_key');
    if (!apiKey) {
      return connectionString;
    }

    let normalized = apiKey.replace(/-/g, '+').replace(/_/g, '/');
    const remainder = normalized.length % 4;
    if (remainder) {
      normalized += '='.repeat(4 - remainder);
    }

    const decoded = JSON.parse(Buffer.from(normalized, 'base64').toString('utf8'));
    return decoded.databaseUrl || connectionString;
  } catch {
    return connectionString;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: decodePrismaPostgresUrl(process.env.DATABASE_URL),
  },
});
